### ISSUE TITLE
GUI: add ‘Explore modified variables’ to microdata tab after creating sdcMicro object

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#100]
After creating the sdcMicro object, the microdata tab has two options: display/rest microdata and explore variables. The explore variables option lets the user explore the raw unanonymized data. Is this meant this way? Please add a third option to the microdata tab ‘Explore modified variables’ and rename the other one ‘Explore original variables’? This makes it possible to check suppressed values, topcodes etc.

**Comment by bernhard-da** [comment]
I would suggest to put this into `Anonymize` - `View/Analyse existing Problem` and create there an option to explore existing variables because I think the microdata view should be really only used for data **before** an sdcProblem has been created. Thus also the restricted choices of methods once an problem instance has been generated.

Is this ok with you?

**Comment by bernhard-da** [comment]
could you please test if everything works as expected?
