### ISSUE TITLE
GUI: enhancement: checks on variable selection

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#111]
On the setup page where the users selects the variables, there are a few checks, e.g., the sdcMicro object cannot be generated in case a numeric variable is selected as categorical key.  The GUI user can see in the button at the bottom of the page, that turns red and includes an error message, what is wrong:
![image002](https://cloud.githubusercontent.com/assets/8253935/19884193/d9b1f61e-a018-11e6-8539-86225db939bc.png)
However, no suggestions are made how to remedy this. I would suggest to introduce either a pop-up window or a line below the button stating how to fix the problem. E.g.: You selected a variable of type 'numeric' as categorical key variables. Convert this variable (even better with the variable name) fiorst to integer or factor and reselect this variable.

**Comment by bernhard-da** [comment]
Hi. I just made a test-implementation using tooltips. You can find this in `ui_setup_sdc.R` from line 525-529.

Could you either come up with a pull request for additional further actions for other checks or list the desired wordings in this issue so that we can add them?

**Comment by thijsbenschop** [comment]
Hi, thanks for this implementation. I'm not sure though whether the user would understand that he has to hover over the button to get more info. I think a pop-up might be more suitable here, since the user will also immediately see this after making the first wrong selection. This would then also solve the question which selection is invalid.

**Comment by bernhard-da** [comment]
I changed now to a modalDialog. This is what you had in mind, right?

**Comment by thijsbenschop** [comment]
Thanks, this is exactly what I had in mind. Also that the button disappears if an invalid selection is made is good.

Could you also add that for the other error messages:

Pop-up window with action in case of ‘red’ setup button: 
-   Error: Selected categorical key variables are of type ‘numeric’ or ‘character’ 
-   Pop-up: Categorical key variables have to be of type ‘factor’ or type ‘integer’. Please go back to the Microdata tab to convert the variables to the appropriate type.
-   Error: Selected continuous key variables are of type ‘factor or ‘character’ 
-   Pop-up: Continuous key variables have to be of type ‘numeric’ or type ‘integer’. Please go back to the Microdata tab to convert the variables to the appropriate type.

**Comment by bernhard-da** [comment]
I have added the proposed pop-ups.

I think - to be consistent - we should also apply popUps for the other checks/errors. Could you please propose some text for the remaining missing ones? These are:
- Error: Selected pram variables are also key-variables
- Error: Selected pram variable is also the weight variable
- Error: Selected pram variable is also the cluster-id variable
- Error: More than one weight variable selected
- Error: Weight variable cannot be selected as (numerical) key-variable
- Error: Weight variable must be of type 'numeric' or 'integer'
- Error: No categorical key variables selected

The last one needs to be some thinking, since it will be TRUE until a categorical key-variable is set. Perhaps we just in this case some info-text to tell the user he has to specify at least one categorical key variable?

**Comment by thijsbenschop** [comment]
Hi,

thanks, I think there are two categories of error messages: 1) those that require to go back to the dataset and change the variable type, and 2) those that can be on the setup page. For the second category, I think the red button provides sufficient information on what to do.

The following error still belongs to the first category:
Error: Weight variable must be of type 'numeric' or 'integer'
Pop-up: The weight variable has to be of type ‘numeric’ or type ‘integer’. Please go back to the Microdata tab to convert the variables to the appropriate type or change the variable type in the dataset and reload the data.

**Comment by bernhard-da** [comment]
I agree with your logic. Implemented the last popup, closing this issue now.
