### ISSUE TITLE
shinyBS is not automatically installed when installing sdcMicro

### ISSUE THREAD

**Issue by cmachingauta** [sdcTools/sdcMicro#114]

**Comment by bernhard-da** [comment]
Yes, this is true because we wanted to experiment a bit with the tooltips. If they prove to be useful, we'll update the required packages.

**Comment by bernhard-da** [comment]
Also, it depends if we keep the GUI directly within sdcMicro or if we just replace the old `sdcGUI` package with the new shiny GUI if we do not want to that users who do not intend to use the GUI have to install a lot of shiny/GUI-related dependencies. We need to decide this before putting the new version on CRAN.

**Comment by cmachingauta** [comment]
Oh OK I see, thanks!

**Comment by thijsbenschop** [comment]
Hi,

I thought we discussed this on Thursday and decided that the GUI would be included in the sdcMicro package and replace the current sdcMicroGUI package. We definitely are in favor of this solution, since this guarantees that the GUI is updated and maintained. I remember that you mentioned that the only disadvantage of this solution would be the sdcMicro user having to install several dependencies he doesn't need. Do you think that adding shinyBS changes this a lot? In that case I would suggest to look for another solution for tooltips rather than having a stand-alone GUI package.

PS: I'm preparing a list of content for the help files and tooltips.
