### ISSUE TITLE
GUI-functionality in sdcMicro or seperate package

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#115]
Hi,

I thought we discussed this on Thursday and decided that the GUI would be included in the sdcMicro package and replace the current sdcMicroGUI package. We definitely are in favor of this solution, since this guarantees that the GUI is updated and maintained. I remember that you mentioned that the only disadvantage of this solution would be the sdcMicro user having to install several dependencies he doesn't need. Do you think that adding shinyBS changes this a lot? In that case I would suggest to look for another solution for tooltips rather than having a stand-alone GUI package.

PS: I'm preparing a list of content for the help files and tooltips.

**Comment by bernhard-da** [comment]
As I said, there are advantages to both possibilities. I am not the maintainer of the package, so I can't decide this in the end.

However, It is not only the shinyBS package, there are some GUI-related packages (`shiny`, `shinyBS`, `DT`, `rhandsontable`, ..) that also have additional dependencies on their own. So since we know that by far not all users want to use the GUI, it would be a quite large overhead for them. Personally, I'd be fine (as I said) with including in in the "core" package as well. We'll decide this on time.

**Comment by bernhard-da** [comment]
perhaps @matthias-da or @alexkowa can share their opinions on this as well.

**Comment by thijsbenschop** [comment]
Ok, as you mentioned it was also one of the requirements in the TOR.

**Comment by matthias-da** [comment]
I agree with Bernhard.

For most users it would be a large overhead to have the GUI included in sdcMicro. On the other hand, the GUI might be updated as soon as sdcMicro is updated when it is included. 

Personally, I think a GUI outside of sdcMicro is better - but this is the message from a guy who prefer command line solutions in any case. 

So, if the requirements is to include it (accoring to the TOR) and if they are written in stone, it is no problem to include it in sdcMicro. Otherwise I tend to have it outside of sdcMicro. Both solutions have their advantages.

**Comment by mwelch750** [comment]
Could we get a sense of what a large overhead would mean. It is typically a once in a while task to install with all dependencies. Our biggest concern is with keeping the GUI in step with sdcMicro - especially with regards to bug fixes, but also functionality in cases where better methods are found. It seems to me the safest way to ensure the two packages remain in step would be to combine them. I will defer to you though on the best method to ensure this. Our concern especially as we will be using this with our client countries is that it be easy to install and as up to date and bug free as possible :-)
