### ISSUE TITLE
GUI: Strata selection is not available on setup screen

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#123]
I cannot see the columns to select pram and strata variable on the setup screen. Is this on purpose so that the user can specify them only for each method? I'm sorry if I missed this discussion.

**Comment by bernhard-da** [comment]
while starting to write the guidelines, i saw that the specification of pram-vars in the gui is actually useless and can be avoided. we simply select all factor variables that are not categorical key variables as pram-vars. in this case, pram can be applied. if it is not applied, no harm is done.

the strata vars are missing due to your input. you said you want to have no stratification by default and want to choose strata variables for each method where it is possible. this is what we have implemented.
