### ISSUE TITLE
Default setting of all variables as pramVar

### ISSUE THREAD

**Issue by mwelch750** [sdcTools/sdcMicro#130]
Hi,

I noticed that all variables not selected as keyVar or weightVar etc are now auto selected as pramVar. is this expected? If so, then could we look are how to display the information on Important Variables on the Establish k-anonymity section as it is essentially listing the whole dataset now - pushing some of the important information way down the screen.

require(sdcMicro)
inputdata <- readMicrodata(path="/tmp/Rtmp8cRlrg/b0b4d58c8ca6623da276a8b5/CaseAlab.dta", type="stata", convertCharToFac=TRUE, drop_all_missings=TRUE)
inputdataB <- inputdata

## Convert a numeric variable to factor with user-specified breaks
inputdata <- varToFactor(obj=inputdata, var=c("AGEYRS"))
## Convert a numeric variable to factor with user-specified breaks
inputdata <- varToFactor(obj=inputdata, var=c("EDYRS"))
## Set up sdcMicro object
sdcObj <- createSdcObj(dat=inputdata,
        keyVars=c("DIST","GENDER","AGEYRS","EDYRS"),
        numVars=c("INCTOTGROSSHH"),
        weightVar=c("WGTPOP"),
        hhId=c("IDH"),
        strataVar=NULL,
        pramVars=c("REGION","URBRUR","REL","MARITAL","RELIG","MORBID","MEASLES","MEDATT","ATSCHOOL","EDUCY","SCHTYP","LITERACY","EMPTYP1","UNEMP1","INDUSTRY1","EMPCAT1","OWNHOUSE","ROOF","TOILET","ELECTCON","FUELCOOK","WATER","OWNAGLAND","OWNMOTORCYCLE","CAR","TV"),
        excludeVars=NULL,
        seed=0,
        randomizeRecords=FALSE,
        alpha=c(0))

 
![image](https://cloud.githubusercontent.com/assets/7872305/20178810/efedc296-a720-11e6-9644-e44ff4be75d3.png)

**Comment by bernhard-da** [comment]
hi.

yes, this is a bit tricky and we need to think a bit how we want to do this. in sdcMicro (command-line), you have to explicitly specify pram-variables. otherwise you cannot apply post-randomization.

a while ago, you or thijs mentioned that it would be a good idea to be able to apply pram to any possible (eg. factor) variable. thus, i realized that the column to specify pram-variables in the setup table was redundant. so i changed the behaviour and set automatically all factors (incl. categorical key variables) as pramvars which leads to the (possibly) long list of pram vars. 

perhaps it is better to re-add the pram-vars column to the setup table and restrict the choice of variables in the pram-section to those variables and add a message in case no variable is left to pram (as it is already now the case when each possible pram-variable has already been postrandomized since we allow only once to apply the method).

**Comment by mwelch750** [comment]
Hi - yes - i wonder if it is not better to enforce a more disciplined approach to setting up the sdcproblem. As such asking users to think a bit about their data and setting up the pram variables more carefully at the outset might be better practice. Thijs - what are your thoughts?

**Comment by cmachingauta** [comment]
In my opinion it's good to have users explicitly specify the pram vars in the set-up table as this encourages users to think about the sdcproblem beforehand and follow a more disciplined approach to it.

**Comment by thijsbenschop** [comment]
I agree that the current default of selecting all remaining variables for PRAM should be changed. We can either reintroduce the column in the setup or set no PRAM vars by default and let the user select the PRAM vars from the list of remaining variables.

**Comment by bernhard-da** [comment]
ok, i reverted that changes. users have to select in the setup table which variables might be postrandomized later. 

added an additional check that these variables must be factor-variables.
