### ISSUE TITLE
Bug: Export labeled Stata file after changes variable label (see #134)

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#135]
Hi,

thanks for including the STATA labeling functions in the GUI (see #134). Everything works as expected. There is only one problem: if I change a variable label in the GUI and subsequently try to export the data in STATA format, the GUI freezes and greys out. This happens with any Stata dataset, e.g., caseA.dta on Box. This doesn't happen if I do not change the variable labels.

**Comment by bernhard-da** [comment]
hi. strange. i do not get a gui freeze. i could reproduce however the issue with `caseA.dta`. it seems that `extractLabels()` does not always return  a list of variable values (the second element of the list). I tested with caseB.dta, where everything worked. could you try again with both datasets (caseA.dta and caseB.dta) and check, if it works now?

**Comment by thijsbenschop** [comment]
Hi, I just tried with caseB.dta and it even greys out and freezes without making changes to the variable labels. Cathrine, do you also experience this problem?

**Comment by bernhard-da** [comment]
do you have any (helpful) message in the R prompt? I still can't reproduce unfortunately.

**Comment by thijsbenschop** [comment]
The following:

Warning: Error in : could not find function "changeVarLabel"
Stack trace (innermost first):
    66: observeEventHandler [/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sdcMicro/shiny-examples/sdcGUI/server.R#1331]
     2: shiny::runApp
     1: sdcGUI
ERROR: [on_request_read] connection reset by peer

However, I didn't change any variable labels.

**Comment by thijsbenschop** [comment]
Can it be that the functions are not exported properly? This is the list of functions I get:

![schermafbeelding 2016-11-14 om 21 12 30](https://cloud.githubusercontent.com/assets/8253935/20281030/267ede94-aaaf-11e6-885f-dfa7873f94cd.png)

All three functions are missing.

**Comment by bernhard-da** [comment]
ok, then it has something to do with your current installation. the reason is that I changed your functions in a way that they are not exported automatically any longer (because they are only used within the GUI).

in `server.R`, `changeVarLabel()` is run whenever you export data to stata, even if you didn't change anything (we can't be sure if you have). so the error tells us that changeVarLabel()` can't be found and thus the GUI freezes out.

I'd recommend to restart clean by removing any prior sdcMicro versions and install the last checkout again.

**Comment by bernhard-da** [comment]
oh, wait a minute. I found the error, fixing it in a second...

**Comment by thijsbenschop** [comment]
Thanks, I'll wait with reinstalling

**Comment by bernhard-da** [comment]
pls try again now...

**Comment by thijsbenschop** [comment]
Thanks, it works now, also after changing some variable names. I can open the files successfully in STATA too.

Two questions:
1) I noticed that variables read as 'labelled' by read_dta appear now with the value labels in the data browser. Is this a (deliberate) change? It is important for the exporting of the value labels to know whether they are the labels or the actual values (see below).
![schermafbeelding 2016-11-14 om 21 31 18](https://cloud.githubusercontent.com/assets/8253935/20281695/b93adad8-aab1-11e6-9083-bf820af3e249.png)

2) Function 54 in the list above is called 'strataVar<-'. Shouldn't that be 'strataVar'?

**Comment by bernhard-da** [comment]
ad 1) this was not really intentional, but what happens is the following: if we have variables of class `labelled`, we convert those to factors using `haven::as_factor`. by default (if labels exist, these are used, but we could also use the values as labels

```
reg <- read_dta("CaseB.dta")$REGION; reg[is.na(reg)] <- NA; class(reg)

# also the default if we omit levels=
table(as_factor(reg, levels="labels"), useNA="always")
Region 1 Region 2 Region 3 Region 4 Region 5 Region 6 Region 7 
    1735     1848     1929     2086     1348        0        0 

# use values as labels
table(as_factor(reg, levels="values"), useNA="always")
   1    2    3    4    5    6    7 <NA> 
1735 1848 1929 2086 1348    0    0 1628 
```

I'd prefer `levels="values"`.

2) no, that's fine. it's a helper function to set stratification variables.

**Comment by thijsbenschop** [comment]
Thanks for your reply. I would also prefer levels = "values". The tables will be easier to read and it is easier to handle for labeling later on.
