### ISSUE TITLE
Accuracy in representation of variables

### ISSUE THREAD

**Issue by cmachingauta** [sdcTools/sdcMicro#136]
![image](https://cloud.githubusercontent.com/assets/7582929/20274653/65c6f042-aa63-11e6-8bd2-0bb33c6330d8.png)

**Comment by bernhard-da** [comment]
First of, we are using `haven::read_dta()` and not `foreign::read.dta()` to read in the data. But anyway, what would be the expected result?

If we read the data using `read_dta()`, we now that somewhere in stata, the information is given that 7 regions are possible.

```
dat <- read_dta("CaseB.dta")
attributes(dat$REGION)$labels
Region 1 Region 2 Region 3 Region 4 Region 5 Region 6 Region 7 
       1        2        3        4        5        6        7  
```

thus, this variable is read into the GUI as a factor with these 7 levels. since no observations are available for region 6 and region 7, these are shown correctly shown having 0 records.  additionally, we have some missing values (`NA`) as well. so i guess everything works as it should.

if region 6 and 7 should not be possible, you would need to change the stata input data set.

**Comment by cmachingauta** [comment]
Hi, in STATA there are only 5 regions, not 7
![image](https://cloud.githubusercontent.com/assets/7582929/20278226/d8fd2c9e-aa71-11e6-87de-5b462423e600.png)

**Comment by mwelch750** [comment]
Cathrine, in Stata can you list the label defined for that variable. Does the label perhaps specify more levels, but because the frequency is zero for some it chooses not to display them in a tab?

**Comment by cmachingauta** [comment]
Oh yes that's probably what happened, I was going to check what the label actually says.  Thanks Matthew

**Comment by cmachingauta** [comment]
Thanks Berhnard!
