### ISSUE TITLE
Crash of GUI after clicking 'k-anonimity' button top apply local suppression

### ISSUE THREAD

**Issue by thijsbenschop** [sdcTools/sdcMicro#164]
While in the middle of anonymizing a file, I wanted to use local suppression. After clicking the local suppression button, the GUI froze and nothing helps to get it going again. This is the error message from the console:

![image](https://cloud.githubusercontent.com/assets/8253935/21048850/bf9f1c0e-be11-11e6-9291-236fe2d3c6f7.png)

Unfortunately, I cannot provide more information, since nothing is retrievable.

**Comment by bernhard-da** [comment]
thx. but having only this information, it is nothing I could do. especially because the warning/error you posted has to do with microaggregation and not with k-anonymity (local suppression). 

please try to reproduce and write down the steps you did, possibly saving the current problem instance before any step you make. thx.

**Comment by thijsbenschop** [comment]
Thanks, will do and hope to soon be able to create a reproducible example.

**Comment by bernhard-da** [comment]
good. i fixed the warning for microaggregation just now.

**Comment by thijsbenschop** [comment]
Thanks
