### ISSUE TITLE
freqCalc fails on recent data.table

### ISSUE THREAD

**Issue by MichaelChirico** [sdcTools/sdcMicro#253]
Hello, in an effort to publish an update to `data.table` to CRAN, we noticed that your package would be broken:

```
install.packages('data.table', type = 'source', repos = 'http://Rdatatable.github.io/data.table')
pkg = 'sdcMicro'
install.packages(pkg, dependencies = TRUE)
library(pkg, character.only = TRUE)
fn = 'freqCalc'
example(fn, character.only = TRUE)
```

> Error in `[.data.table`(dat_with_na, , `:=`(tmpid, .I)) : Cannot use := to add columns to a null data.table (no columns), currently. You can use := to add (empty) columns to a 0-row data.table (1 or more empty columns), though.

From a quick glance at your code, you'll need to add a test for whether `dat_with_na` has any columns before attempting to assign to it; this may be required at other places in your code base as well.

**Comment by GregorDeCillia** [comment]
Thank you very much for reporting this.

The issue was actually related to some changes in `merge` where column names got suffixed while they didn't previously. However, there is still a second problem with the `freqCalc` function in the `localSuppression ` examples. That second one seems to be related to changes in `na.omit`. See [data.table/#2784](https://github.com/Rdatatable/data.table/issues/2784).

**Comment by MichaelChirico** [comment]
OK thanks for investigating. A fix should come soon as we're really behind the eight ball getting to CRAN since `3.5.0` was released.

**Comment by mattdowle** [comment]
Thanks @GregorDeCillia !  Will fix na.omit before release.
