### ISSUE TITLE
issue in rankSwap: not able to specify rank range with parameter P

### ISSUE THREAD

**Issue by santalw** [sdcTools/sdcMicro#277]
The P parameter in rankSwap() function seems not working properly.

By default, P = 0, meaning that if the user does not provide a value for P parameter, no record will be swapped. However, it has been observed that almost all record got swapped in the output without specifying P parameter.

For another example, I run the following case to test the range of swapping:
a <- c(1:10000)
test <- as.data.frame(a)
swapped <-rankSwap(test, var = c("a"), P = 0.02)

According to the formula provided in arguments description, the records that are eligible for swapping need to satisfy abs(i-j) < 0.02*10000/100 = 2. Therefore, in theory only the records next to each other can be swapped. However, in the actual output, the maximum swap range can be over 800.

Please advice if P parameter is working, and in the case where no value is specified for P parameter, what is the default rank range. 
Thanks!

**Comment by alexkowa** [comment]
Thank you for your comment the parameters are a bit strange: 
P is just ignored per default because a positive R0 is the default so this overrules the P.
you can use P by setting R0 to -1
`swapped <-rankSwap(test, var = c("a"), P = 0,TopPercent=0, BottomPercent=0,R0=-1)`

I tried to make the parameters more R-like by setting the default values to NULL and giving an error if more than one parameter is provided.
So in the github version this code should work:
`swapped <-rankSwap(test, var = c("a"), P = 0,TopPercent=0, BottomPercent=0,R0=NULL)`

TODO: @bernhard-da or myself adjust sdcApp accordingly
