### ISSUE TITLE
Numeric risk computation after microaggregation?

### ISSUE THREAD

**Issue by alexkowa** [sdcTools/sdcMicro#35]
set.seed( 657613 )
activedataset <- testdata
sdcObject <- createSdcObj(activedataset,keyVars=c('urbrur','roof','walls'),numVars=c('income'),weightVar=c('sampling_weight'),hhId=c('ori_hid'))
sdcObject <- microaggregation(sdcObject,aggr=c( 3 ), method=c('mdav'), variables=c('income'))
sdcObject <- microaggregation(sdcObject,aggr=c( 3 ), method=c('mdav'), variables=c('income'),strata_variables=c('urbrur'))
sdcObject@risk$numeric
s=dRisk(sdcObject)
s@risk$numeric

**Comment by bernhard-da** [comment]
stupid things....

**Comment by bernhard-da** [comment]
should be alright, probably an error when only one numVar. but the following works as it should...

activedataset <- free1
sdcObject <- createSdcObj(activedataset,keyVars=c('SEX','MARSTAT','REGION'),numVars=c('INCOME',"MONEY"),weightVar=c('WEIGHT'),hhId=NULL)

sdcObject <- microaggregation(sdcObject,aggr=c( 3 ), method=c('mdav'), variables=c('INCOME',"MONEY"))
a1 <- dRisk(sdcObject)@risk
sdcObject <- microaggregation(sdcObject,aggr=c( 5 ), method=c('mdav'), variables=c('INCOME',"MONEY"))
a2 <- dRisk(sdcObject)@risk
sdcObject <- microaggregation(sdcObject,aggr=c( 10 ), method=c('mdav'), variables=c('INCOME',"MONEY"))
a3 <- dRisk(sdcObject)@risk

print(c(a1$numeric, a2$numeric, a3$numeric))

**Comment by alexkowa** [comment]
no error -> but dRisk computes for small number of variables a very high risk: possible solution:
- use dRiskRMD additionally (maybe with a button in the GUI) = not feasible for large data set
- invent sth new?!

**Comment by matthias-da** [comment]
for microaggregation the current risk measure is not suitable (see guidelines).
- we may put a warning in the GUI whenever somebody do microaggregation. The warning might be:
  "risk measure is not fully applicable for microaggregated data, see IHSN SDC Introduction for details"
- or alternatively we program a new risk measure. Proposal based on merging (only visible for small data sets, therefore:)
  a) only for large data values (univariate decision regarding "largeness" because of large data sets (MCD not possible)) we merge each observation from the perturbed continuous variables (multivariate if more than one cont. key var) to the original continuous variables (multivariate). The percentage of correct matches is a risk measure.

**Comment by alexkowa** [comment]
I think it is enough when it is in the guidelines.
