### ISSUE TITLE
Behaviour of kAnon when combs = 2

### ISSUE THREAD

**Issue by matthias-da** [sdcTools/sdcMicro#352]
Behaviour of `kAnon` with `"combs = 2"`

Example (form MonteroSerrano, Javier) where `kAnon` with `combs = 2` fails to protect province-activity combination.
Note that `alpha = 0`.

```{r}
# Create data
data_4 <- data.frame(
    province = factor(c(2,3,3,2,4,2,4,2,2,3)),
    activity = factor(c("A","A","A","A","B","B","B","B","A","A")),
    sex = factor(c("Female","Female","Female","Male","Female","Female","Female","Female","Male","Male")),
    income = factor(c("high","low","low","low","high","medium","high","low","high","medium")))

# Create sdc object
sdc_data_4 <- createSdcObj(data_4, keyVars = c("province", "activity", "sex", "income"), alpha = 0)

# kAnon with "combs = 2" .
sdc_data_kAnon_c2 <- kAnon(sdc_data_4, k = 3, combs = 2)

sdc_data_2keyvars <- createSdcObj(extractManipData(sdc_data_kAnon_c2), keyVars = c("province", "activity"), alpha = 0)
sdc_data_2keyvars@origData %>% dplyr::bind_cols(fk = sdc_data_2keyvars@risk[["individual"]][,"fk"])
```
The two records "2-A" do not reach `fk = 3` (despite `keyVars` being restricted to `"province"` and `"activity"` only)

Please check if this is the expected behavior (I think it is not).

**Comment by bernhard-da** [comment]
This is indeed a bit tricky. The issue is that the current way k-Anonymity is obtained for combinations of key-variables is iterative. Therefore it can happen (and happened in this case) that a specific combination (e.g `province` x `activity`) is handled and the required suppressions in order to achieve k-anonymity is performed (taking alpha = 0 into account as in the example). Later in the process, another combination of variables that either contains `province` or `activity` is considered and additional supps are deemed required for any of this variable to achieve k-anonymity for this subset of key variables. These additional suppressions may lead to a change of keys in the already considered subset of vars. For illustration:

In the initial consideration of combination `province` x `activity` we could have keys `2-A` and `2-NA` both occuring `3` times thus none of those keys violating `3`-anonymity. When considering the combination `income` x `activity` it could have been that values of `A` in variable `acitivity` had to be additionally suppressed. That could lead (when looking only at `province` x `activity`)  that the distribution of keys had changed into key `2-A` now occuring less than 3 times and and `2-NA` now occuring more than 3 times. This is indeed what was this example shows.

For `alpha=1` (the default) this is not a problem since additionally suppressing values can only increase fk. For alpha = 0 (as in this case) this can lead to the observed behavior. But I would also say that this is not a problem for practical reasons. But perhaps we should introduce a message/warning that `alpha=0` may lead to somewhat difficult to consider results when using `kAnon()` in together with combinations. What do you think @matthias-da ?

**Comment by matthias-da** [comment]
Thank you very much, Bernhard. I see, this is all because of the heuristic algorithm of `kAnon`. I extended the help file and uploaded it already to the main branch of sdcMicro. Would be helpful if you proofread (and modify) them.

**Comment by bernhard-da** [comment]
yes, combination of heuristic + alpha = 0; i'll proofread for sure
