### ISSUE TITLE
bug in pram

### ISSUE THREAD

**Issue by matthias-da** [sdcTools/sdcMicro#41]
require(sdcMicro); data(testdata)
sdc <- createSdcObj(testdata, 
 keyVars=c('urbrur','water','sex','age'), 
 numVars=c('expend','income','savings'), 
 #pramVars=c("walls"),
 w='sampling_weight', 
 hhId='ori_hid')

sdc <- pram(sdc)
# error

sdc <- createSdcObj(testdata, 
 keyVars=c('urbrur','water','sex','age'), 
 numVars=c('expend','income','savings'), 
 pramVars=c("walls"),
 w='sampling_weight', 
 hhId='ori_hid')

sdc <- pram(sdc)
# error

**Comment by alexkowa** [comment]
The error message is a real error not a bug, it is intentional that if not variable to be prammed is selected (default for argument variables=NULL) => Error
This works:
require(sdcMicro); data(testdata)
sdc <- createSdcObj(testdata, 
    keyVars=c('urbrur','water','sex','age'), 
    numVars=c('expend','income','savings'), 
#pramVars=c("walls"),
    w='sampling_weight', 
    hhId='ori_hid')

sdc <- pram(sdc,variables=c("walls","electcon"))
sdc <- pram(sdc,variables=c("walls","water"))#with warning because water is a key variable

**Comment by alexkowa** [comment]
COMMENT FROM BERNHARD, was in the wrong thread:
i think we should stop with an error if slot pramVars is NULL and argument 'variables' is not specified.

thoughts?

```
setMethod(f='pram', signature=c('sdcMicroObj'),
    definition=function(obj, variables=NULL,strata_variables=NULL,pd=0.8, alpha=0.5) { 
    ### Get data from manipPramVars

  manipPramVars <- get.sdcMicroObj(obj, type="manipPramVars")
  pramVars <- colnames(obj@origData)[get.sdcMicroObj(obj, type="pramVars")]

    ## we return an error if slot pramVars is empty 
    # and no variables have been specified to be used for pram
    if ( length(pramVars) == 0 & is.null(variables) ) {
        stop("Error: slot pramVars is NULL and argument 'variables' was not specified!\n")
    }

    strataVars <- ...
```
